<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="qcore" nsURI="http://dsie.upct.es/lsi/qcore" nsPrefix="qcore">
  <eClassifiers xsi:type="ecore:EClass" name="Circuit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="qubits" lowerBound="1"
        upperBound="-1" eType="#//Qubit" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//Edge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Control" eSuperTypes="#//QuantumGate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlGate" lowerBound="1"
        eType="#//QuantumGate" eOpposite="#//QuantumGate/controlledBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H" eSuperTypes="#//QuantumGate"/>
  <eClassifiers xsi:type="ecore:EClass" name="QuantumGate" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="qubit" lowerBound="1" eType="#//Qubit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlledBy" upperBound="-1"
        eType="#//Control" eOpposite="#//Control/controlGate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//Node"
        eOpposite="#//Node/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dst" lowerBound="1" eType="#//Node"
        eOpposite="#//Node/incoming"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Qubit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gates" upperBound="-1"
        eType="#//QuantumGate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAncilla" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gates" lowerBound="1" upperBound="-1"
        eType="#//QuantumGate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//Edge" eOpposite="#//Edge/dst"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//Edge" eOpposite="#//Edge/src"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="X" eSuperTypes="#//QuantumGate"/>
  <eClassifiers xsi:type="ecore:EClass" name="Z" eSuperTypes="#//QuantumGate"/>
</ecore:EPackage>
